### ISSUE TITLE
Figure out how to grab user info from Firebase

### ISSUE THREAD

**Issue by hmc-cs-azhao** [Sangheetha/Walking-School-Bus-Web-App#3]
As the user, I want to have access to a page that gives information for the staff member walking my child, my own information, and my child's information to keep track of who my child is with.

**Comment by alleyb** [comment]
https://www.firebase.com/docs/web/guide/retrieving-data.html

**Comment by alleyb** [comment]
http://stackoverflow.com/questions/14963776/get-users-by-name-property-using-firebase
